# octocov configuration
# https://github.com/k1LoW/octocov

coverage:
  paths:
    - coverage/lcov.info

body:
  enable: true

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
