# octocov configuration
# https://github.com/k1LoW/octocov

coverage:
  paths:
    - coverage/lcov.info

body:
  enable: true
  hideFooterLink: true

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
