/**
 * Runtime dispatcher completion generators.
 *
 * Dispatcher scripts keep no command tree in the shell. At TAB time they
 * resolve the executable visible on PATH (or the explicit <PROGRAM>_BIN
 * override), call its hidden `__complete` command, and translate the returned
 * candidate stream into native shell completion calls.
 */

import type { AnyCommand } from "../types.js";
import { CompletionDirective } from "./dynamic/candidate-generator.js";
import { binEnvVarName, sanitize } from "./extractor.js";
import { buildHeaderLines } from "./header.js";
import type { CompletionOptions, CompletionResult } from "./types.js";

function shSingleQuote(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}

function compileCacheSuffix(programName: string): string {
  return shSingleQuote(`/${programName}/node-compile-cache`);
}

function hardcodedCompileCacheDir(cacheDir: string | undefined): string | undefined {
  return cacheDir ? shSingleQuote(`${cacheDir}/node-compile-cache`) : undefined;
}

function hardcodedWorkerPath(cacheDir: string | undefined, shell: string): string | undefined {
  return cacheDir ? shSingleQuote(`${cacheDir}/completion-worker.${shell}`) : undefined;
}

function workerPathSuffix(programName: string, shell: string): string {
  return shSingleQuote(`/${programName}/completion-worker.${shell}`);
}

function statSigExpr(): string {
  return `$(stat -L -c '%Y' "$_bin" 2>/dev/null || stat -L -f '%m' "$_bin" 2>/dev/null)`;
}

function bashDispatcher(_command: AnyCommand, options: CompletionOptions): CompletionResult {
  const { programName } = options;
  const fn = sanitize(programName);
  const workerFn = `${fn}_worker`;
  const workerBinEnvName = binEnvVarName(workerFn);
  const envName = binEnvVarName(fn);
  const programLookup = shSingleQuote(programName);
  const compileCacheDir = hardcodedCompileCacheDir(options.cacheDir);
  const compileCacheDefault = compileCacheDir
    ? `        printf '%s\\n' ${compileCacheDir}`
    : `        printf '%s\\n' "\${XDG_CACHE_HOME:-$HOME/.cache}"${compileCacheSuffix(programName)}`;
  const workerPath = hardcodedWorkerPath(options.cacheDir, "bash");
  const workerPathDefault = workerPath
    ? `        printf '%s\\n' ${workerPath}`
    : `        printf '%s\\n' "\${XDG_CACHE_HOME:-$HOME/.cache}"${workerPathSuffix(programName, "bash")}`;

  const lines: string[] = [];
  lines.push(
    ...buildHeaderLines({
      programName,
      shell: "bash",
      binPath: options.binPath,
      programVersion: options.programVersion,
    }),
  );
  lines.push(`# Generated by politty`);
  lines.push(`# politty-completion-mode: dispatcher`);
  lines.push(``);
  lines.push(`__${fn}_resolve_bin() {`);
  lines.push(`    if [[ -n "\${${envName}:-}" ]]; then`);
  lines.push(`        printf '%s\\n' "\${${envName}}"`);
  lines.push(`        return 0`);
  lines.push(`    fi`);
  lines.push(`    type -P ${programLookup} 2>/dev/null`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_node_compile_cache_dir() {`);
  lines.push(`    if [[ -n "\${NODE_COMPILE_CACHE:-}" ]]; then`);
  lines.push(`        printf '%s\\n' "$NODE_COMPILE_CACHE"`);
  lines.push(`        return 0`);
  lines.push(`    fi`);
  lines.push(compileCacheDefault);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_static_worker_path() {`);
  lines.push(workerPathDefault);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_bin_sig() {`);
  lines.push(`    local _bin="$1" _sig`);
  lines.push(`    _sig=${statSigExpr()} || return 1`);
  lines.push(`    printf '%s\\n' "$_sig"`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_apply_dynamic_output() {`);
  lines.push(`    local _raw="$1" _cur="$2" _inline_prefix="$3"`);
  lines.push(`    COMPREPLY=()`);
  lines.push(`    local _directive=0`);
  lines.push(`    local -a _lines=() _exts=() _matchers=()`);
  lines.push(`    local _line`);
  lines.push(`    while IFS= read -r _line; do _lines+=("$_line"); done <<< "$_raw"`);
  lines.push(`    local _last=$((\${#_lines[@]} - 1))`);
  lines.push(`    if (( _last >= 0 )) && [[ "\${_lines[$_last]}" =~ ^:[0-9]+$ ]]; then`);
  lines.push(`        _directive="\${_lines[$_last]#:}"`);
  lines.push(`        unset '_lines[_last]'`);
  lines.push(`    fi`);
  lines.push(`    for _line in "\${_lines[@]}"; do`);
  lines.push(`        [[ -z "$_line" ]] && continue`);
  lines.push(`        if [[ "$_line" == @ext:* ]]; then`);
  lines.push(`            IFS=',' read -r -a _exts <<< "\${_line#@ext:}"`);
  lines.push(`        elif [[ "$_line" == @matcher:* ]]; then`);
  lines.push(`            IFS=',' read -r -a _matchers <<< "\${_line#@matcher:}"`);
  lines.push(`        else`);
  lines.push(`            COMPREPLY+=("$_line")`);
  lines.push(`        fi`);
  lines.push(`    done`);
  lines.push(`    local _ip="\${_inline_prefix:-}"`);
  lines.push(`    if (( \${#_exts[@]} > 0 || \${#_matchers[@]} > 0 )); then`);
  lines.push(`        compopt +o default 2>/dev/null`);
  lines.push(`        compopt -o filenames 2>/dev/null`);
  lines.push(`        local _f _ext _pat _base _ok`);
  lines.push(`        while IFS= read -r _f; do`);
  lines.push(`            if [[ -d "$_f" ]]; then`);
  lines.push(`                COMPREPLY+=("\${_ip}\${_f}")`);
  lines.push(`                continue`);
  lines.push(`            fi`);
  lines.push(`            _ok=0`);
  lines.push(`            if (( \${#_exts[@]} > 0 )); then`);
  lines.push(`                for _ext in "\${_exts[@]}"; do`);
  lines.push(`                    [[ -n "$_ext" && "$_f" == *."$_ext" ]] && _ok=1`);
  lines.push(`                done`);
  lines.push(`            fi`);
  lines.push(`            if (( \${#_matchers[@]} > 0 )); then`);
  lines.push(`                _base="\${_f##*/}"`);
  lines.push(`                for _pat in "\${_matchers[@]}"; do`);
  lines.push(`                    [[ -n "$_pat" && "$_base" == $_pat ]] && _ok=1`);
  lines.push(`                done`);
  lines.push(`            fi`);
  lines.push(`            (( _ok )) && COMPREPLY+=("\${_ip}\${_f}")`);
  lines.push(`        done < <(compgen -f -- "$_cur")`);
  lines.push(`    elif (( _directive & ${CompletionDirective.DirectoryCompletion} )); then`);
  lines.push(`        compopt +o default 2>/dev/null`);
  lines.push(`        compopt -o filenames 2>/dev/null`);
  lines.push(`        local _d`);
  lines.push(
    `        while IFS= read -r _d; do COMPREPLY+=("\${_ip}\${_d}"); done < <(compgen -d -- "$_cur")`,
  );
  lines.push(`        if (( \${#COMPREPLY[@]} == 0 )); then COMPREPLY=( "" ); fi`);
  lines.push(`    elif (( _directive & ${CompletionDirective.FileCompletion} )); then`);
  lines.push(`        compopt -o filenames 2>/dev/null`);
  lines.push(`        local _p`);
  lines.push(
    `        while IFS= read -r _p; do COMPREPLY+=("\${_ip}\${_p}"); done < <(compgen -f -- "$_cur")`,
  );
  lines.push(`    elif (( _directive & ${CompletionDirective.NoFileCompletion} )); then`);
  lines.push(`        compopt +o default 2>/dev/null`);
  lines.push(`    fi`);
  lines.push(`    if (( _directive & ${CompletionDirective.NoSpace} )); then`);
  lines.push(`        compopt -o nospace 2>/dev/null`);
  lines.push(`    fi`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`_${fn}_completions() {`);
  lines.push(`    COMPREPLY=()`);
  lines.push(`    local -a _words=()`);
  lines.push(`    local _i=1`);
  lines.push(`    while (( _i <= COMP_CWORD )); do`);
  lines.push(`        if [[ "\${COMP_WORDS[_i]}" == "=" && \${#_words[@]} -gt 0 ]]; then`);
  lines.push(`            _words[\${#_words[@]}-1]+="=\${COMP_WORDS[_i+1]:-}"`);
  lines.push(`            (( _i += 2 ))`);
  lines.push(`        else`);
  lines.push(`            _words+=("\${COMP_WORDS[_i]}")`);
  lines.push(`            (( _i++ ))`);
  lines.push(`        fi`);
  lines.push(`    done`);
  lines.push(`    local _cur="" _inline_prefix=""`);
  lines.push(`    (( \${#_words[@]} > 0 )) && _cur="\${_words[\${#_words[@]}-1]}"`);
  lines.push(`    if [[ "$_cur" == -*=* ]]; then`);
  lines.push(`        _inline_prefix="\${_cur%%=*}="`);
  lines.push(`        _cur="\${_cur#*=}"`);
  lines.push(`    fi`);
  lines.push(`    local _bin _out _node_compile_cache _worker _sig`);
  lines.push(`    _bin="$(__${fn}_resolve_bin)"`);
  lines.push(`    [[ -n "$_bin" ]] || return 0`);
  lines.push(`    _node_compile_cache="$(__${fn}_node_compile_cache_dir)"`);
  lines.push(`    _worker="$(__${fn}_static_worker_path)"`);
  lines.push(`    _sig="$(__${fn}_bin_sig "$_bin")"`);
  lines.push(`    if [[ -n "$_worker" && -n "$_sig" ]]; then`);
  lines.push(
    `        if [[ ! -f "$_worker" ]] || ! head -n 10 "$_worker" 2>/dev/null | grep -qF "# politty-bin-sig: $_sig"; then`,
  );
  lines.push(`            mkdir -p "\${_worker%/*}" 2>/dev/null`);
  lines.push(
    `            NODE_COMPILE_CACHE="$_node_compile_cache" ${envName}="$_bin" "$_bin" __refresh-completion bash "$_worker" --static --worker 2>/dev/null`,
  );
  lines.push(`        fi`);
  lines.push(`        if [[ -f "$_worker" ]] && source "$_worker" 2>/dev/null; then`);
  lines.push(`            ${workerBinEnvName}="$_bin" _${workerFn}_completions`);
  lines.push(`            return 0`);
  lines.push(`        fi`);
  lines.push(`    fi`);
  lines.push(
    `    _out=$(NODE_COMPILE_CACHE="$_node_compile_cache" "$_bin" __complete --shell bash -- "\${_words[@]}" 2>/dev/null) || return 0`,
  );
  lines.push(`    __${fn}_apply_dynamic_output "$_out" "$_cur" "$_inline_prefix"`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`complete -o default -F _${fn}_completions ${programName}`);
  lines.push(``);

  return {
    script: lines.join("\n"),
    shell: "bash",
    installInstructions: `# To enable dispatcher bash completions, add this to your ~/.bashrc:
eval "$(${programName} completion bash)"

# To save the dispatcher script instead:
mkdir -p ~/.local/share/bash-completion/completions
${programName} completion bash > ~/.local/share/bash-completion/completions/${programName}

# To generate the older static script:
${programName} completion bash --static`,
  };
}

function zshDispatcher(_command: AnyCommand, options: CompletionOptions): CompletionResult {
  const { programName } = options;
  const fn = sanitize(programName);
  const workerFn = `${fn}_worker`;
  const workerBinEnvName = binEnvVarName(workerFn);
  const envName = binEnvVarName(fn);
  const programLookup = shSingleQuote(programName);
  const completionFn = `_${programName}`;
  const autoloadCheck = `"${"${funcstack[1]:-}"}" == "${completionFn}"`;
  const compileCacheDir = hardcodedCompileCacheDir(options.cacheDir);
  const compileCacheDefault = compileCacheDir
    ? `        print -r -- ${compileCacheDir}`
    : `        print -r -- "\${XDG_CACHE_HOME:-$HOME/.cache}"${compileCacheSuffix(programName)}`;
  const workerPath = hardcodedWorkerPath(options.cacheDir, "zsh");
  const workerPathDefault = workerPath
    ? `        print -r -- ${workerPath}`
    : `        print -r -- "\${XDG_CACHE_HOME:-$HOME/.cache}"${workerPathSuffix(programName, "zsh")}`;

  const lines: string[] = [];
  lines.push(`#compdef ${programName}`);
  lines.push(
    ...buildHeaderLines({
      programName,
      shell: "zsh",
      binPath: options.binPath,
      programVersion: options.programVersion,
    }),
  );
  lines.push(`# Generated by politty`);
  lines.push(`# politty-completion-mode: dispatcher`);
  lines.push(``);
  lines.push(`__${fn}_resolve_bin() {`);
  lines.push(`    emulate -L zsh`);
  lines.push(`    setopt local_options no_aliases`);
  lines.push(`    if [[ -n "\${${envName}:-}" ]]; then`);
  lines.push(`        print -r -- "\${${envName}}"`);
  lines.push(`        return 0`);
  lines.push(`    fi`);
  lines.push(`    whence -p ${programLookup} 2>/dev/null`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_node_compile_cache_dir() {`);
  lines.push(`    emulate -L zsh`);
  lines.push(`    setopt local_options no_aliases`);
  lines.push(`    if [[ -n "\${NODE_COMPILE_CACHE:-}" ]]; then`);
  lines.push(`        print -r -- "$NODE_COMPILE_CACHE"`);
  lines.push(`        return 0`);
  lines.push(`    fi`);
  lines.push(compileCacheDefault);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_static_worker_path() {`);
  lines.push(`    emulate -L zsh`);
  lines.push(`    setopt local_options no_aliases`);
  lines.push(workerPathDefault);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_bin_sig() {`);
  lines.push(`    emulate -L zsh`);
  lines.push(`    setopt local_options no_aliases`);
  lines.push(`    local _bin="$1" _sig`);
  lines.push(`    _sig=${statSigExpr()} || return 1`);
  lines.push(`    print -r -- "$_sig"`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_cdescribe() {`);
  lines.push(`    _describe "$@" 2>/dev/null && return 0`);
  lines.push(`    shift`);
  lines.push(`    local _cd_arr="$1"`);
  lines.push(`    shift`);
  lines.push(`    local -a _cd_vals=("\${(@)\${(P)_cd_arr}%%:*}")`);
  lines.push(`    compadd "$@" -a _cd_vals 2>/dev/null`);
  lines.push(`    return 0`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_add_path_candidate() {`);
  lines.push(`    compadd -f -- "$1" 2>/dev/null && return 0`);
  lines.push(`    print -r -- "$1"`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`__${fn}_apply_dynamic_output() {`);
  lines.push(`    local _raw="$1"`);
  lines.push(`    local _directive=0`);
  lines.push(`    local -a _vals _lines _exts _matchers`);
  lines.push(`    local _meta`);
  lines.push(`    _lines=("\${(@f)_raw}")`);
  lines.push(`    local _last=$#_lines`);
  lines.push(`    if (( _last >= 1 )) && [[ "\${_lines[$_last]}" == :<-> ]]; then`);
  lines.push(`        _directive="\${_lines[$_last]#:}"`);
  lines.push(`        _lines[$_last]=()`);
  lines.push(`    fi`);
  lines.push(`    local _l`);
  lines.push(`    for _l in "\${_lines[@]}"; do`);
  lines.push(`        [[ -z "$_l" ]] && continue`);
  lines.push(`        if [[ "$_l" == @ext:* ]]; then`);
  lines.push(`            _meta="\${_l#@ext:}"`);
  lines.push(`            _exts=("\${(@s:,:)_meta}")`);
  lines.push(`        elif [[ "$_l" == @matcher:* ]]; then`);
  lines.push(`            _meta="\${_l#@matcher:}"`);
  lines.push(`            _matchers=("\${(@s:,:)_meta}")`);
  lines.push(`        else`);
  lines.push(`            _vals+=("$_l")`);
  lines.push(`        fi`);
  lines.push(`    done`);
  lines.push(`    if (( \${#_vals[@]} > 0 )); then`);
  lines.push(`        if (( _directive & ${CompletionDirective.NoSpace} )); then`);
  lines.push(`            __${fn}_cdescribe 'completions' _vals -S ''`);
  lines.push(`        else`);
  lines.push(`            __${fn}_cdescribe 'completions' _vals`);
  lines.push(`        fi`);
  lines.push(`    fi`);
  lines.push(`    if (( \${#_exts[@]} > 0 || \${#_matchers[@]} > 0 )); then`);
  lines.push(`        setopt local_options null_glob`);
  lines.push(`        local _cur="\${words[CURRENT]:-}" _dir _prefix _f _out _ext _pat`);
  lines.push(`        if [[ -z "$_cur" || "$_cur" != */* ]]; then`);
  lines.push(`            _dir="."`);
  lines.push(`            _prefix="$_cur"`);
  lines.push(`        elif [[ "$_cur" == */ ]]; then`);
  lines.push(`            _dir="\${_cur%/}"`);
  lines.push(`            _prefix=""`);
  lines.push(`        else`);
  lines.push(`            _dir="\${_cur%/*}"`);
  lines.push(`            _prefix="\${_cur##*/}"`);
  lines.push(`        fi`);
  lines.push(`        for _f in "$_dir"/"$_prefix"*(N/); do`);
  lines.push(`            _out="\${_f#./}"`);
  lines.push(`            __${fn}_add_path_candidate "$_out"`);
  lines.push(`        done`);
  lines.push(`        for _ext in "\${_exts[@]}"; do`);
  lines.push(`            [[ -n "$_ext" ]] || continue`);
  lines.push(`            for _f in "$_dir"/"$_prefix"*."$_ext"(N.); do`);
  lines.push(`                _out="\${_f#./}"`);
  lines.push(`                __${fn}_add_path_candidate "$_out"`);
  lines.push(`            done`);
  lines.push(`        done`);
  lines.push(`        for _pat in "\${_matchers[@]}"; do`);
  lines.push(`            [[ -n "$_pat" ]] || continue`);
  lines.push(`            for _f in "$_dir"/$_pat(N.); do`);
  lines.push(`                _out="\${_f#./}"`);
  lines.push(`                [[ "$_out" == "$_cur"* ]] && __${fn}_add_path_candidate "$_out"`);
  lines.push(`            done`);
  lines.push(`        done`);
  lines.push(`    elif (( _directive & ${CompletionDirective.DirectoryCompletion} )); then`);
  lines.push(`        _files -/`);
  lines.push(`    elif (( _directive & ${CompletionDirective.FileCompletion} )); then`);
  lines.push(`        _files`);
  lines.push(
    `    elif (( \${#_vals[@]} == 0 )) && ! (( _directive & ${CompletionDirective.NoFileCompletion} )); then`,
  );
  lines.push(`        _files`);
  lines.push(`    fi`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`${completionFn}() {`);
  lines.push(`    emulate -L zsh`);
  lines.push(`    setopt local_options no_aliases`);
  lines.push(`    local _bin _out _node_compile_cache _worker _sig`);
  lines.push(`    _bin="$(__${fn}_resolve_bin)"`);
  lines.push(`    [[ -n "$_bin" ]] || return 1`);
  lines.push(`    _node_compile_cache="$(__${fn}_node_compile_cache_dir)"`);
  lines.push(`    _worker="$(__${fn}_static_worker_path)"`);
  lines.push(`    _sig="$(__${fn}_bin_sig "$_bin")"`);
  lines.push(`    if [[ -n "$_worker" && -n "$_sig" ]]; then`);
  lines.push(
    `        if [[ ! -f "$_worker" ]] || ! head -n 10 "$_worker" 2>/dev/null | grep -qF "# politty-bin-sig: $_sig"; then`,
  );
  lines.push(`            mkdir -p "\${_worker%/*}" 2>/dev/null`);
  lines.push(
    `            NODE_COMPILE_CACHE="$_node_compile_cache" ${envName}="$_bin" "$_bin" __refresh-completion zsh "$_worker" --static --worker 2>/dev/null`,
  );
  lines.push(`        fi`);
  lines.push(`        if [[ -f "$_worker" ]] && source "$_worker" 2>/dev/null; then`);
  lines.push(`            ${workerBinEnvName}="$_bin" _${workerFn}_completions "$@"`);
  lines.push(`            return 0`);
  lines.push(`        fi`);
  lines.push(`    fi`);
  lines.push(
    `    _out=$(NODE_COMPILE_CACHE="$_node_compile_cache" "$_bin" __complete --shell zsh -- "\${(@)words[2,CURRENT]}" 2>/dev/null) || return 1`,
  );
  lines.push(`    __${fn}_apply_dynamic_output "$_out"`);
  lines.push(`}`);
  lines.push(``);
  lines.push(
    `zstyle ':completion:*:*:${programName}:*' file-patterns '%p:globbed-files *(-/):directories'`,
  );
  lines.push(``);
  lines.push(`if [[ ${autoloadCheck} ]]; then`);
  lines.push(`    ${completionFn} "$@"`);
  lines.push(`else`);
  lines.push(`    compdef ${completionFn} ${programName}`);
  lines.push(`fi`);
  lines.push(``);

  return {
    script: lines.join("\n"),
    shell: "zsh",
    installInstructions: `# To enable dispatcher zsh completions, add this to your ~/.zshrc after compinit:
eval "$(${programName} completion zsh)"

# To save the dispatcher script in your fpath:
mkdir -p ~/.zsh/completions
${programName} completion zsh > ~/.zsh/completions/_${programName}

# Make sure your ~/.zshrc includes the fpath line before compinit:
fpath=(~/.zsh/completions $fpath)
autoload -Uz compinit && compinit

# To generate the older static script:
${programName} completion zsh --static`,
  };
}

function fishDispatcher(_command: AnyCommand, options: CompletionOptions): CompletionResult {
  const { programName } = options;
  const fn = sanitize(programName);
  const workerFn = `${fn}_worker`;
  const workerBinEnvName = binEnvVarName(workerFn);
  const envName = binEnvVarName(fn);
  const programLookup = shSingleQuote(programName);
  const compileCacheDir = hardcodedCompileCacheDir(options.cacheDir);
  const compileCacheDefault = compileCacheDir
    ? `    printf '%s\\n' ${compileCacheDir}`
    : [
        `    set -l _cache_root "$XDG_CACHE_HOME"`,
        `    test -n "$_cache_root"; or set _cache_root "$HOME/.cache"`,
        `    printf '%s\\n' "$_cache_root"${compileCacheSuffix(programName)}`,
      ].join("\n");
  const workerPath = hardcodedWorkerPath(options.cacheDir, "fish");
  const workerPathDefault = workerPath
    ? `    printf '%s\\n' ${workerPath}`
    : [
        `    set -l _cache_root "$XDG_CACHE_HOME"`,
        `    test -n "$_cache_root"; or set _cache_root "$HOME/.cache"`,
        `    printf '%s\\n' "$_cache_root"${workerPathSuffix(programName, "fish")}`,
      ].join("\n");

  const lines: string[] = [];
  lines.push(
    ...buildHeaderLines({
      programName,
      shell: "fish",
      binPath: options.binPath,
      programVersion: options.programVersion,
    }),
  );
  lines.push(`# Generated by politty`);
  lines.push(`# politty-completion-mode: dispatcher`);
  lines.push(``);
  lines.push(`function __${fn}_resolve_bin`);
  lines.push(`    if set -q ${envName}; and test -n "$${envName}"`);
  lines.push(`        printf '%s\\n' "$${envName}"`);
  lines.push(`        return 0`);
  lines.push(`    end`);
  lines.push(`    set -l _bin (command -v ${programLookup})`);
  lines.push(
    `    test -n "$_bin"; and test -x "$_bin"; and not test -d "$_bin"; and printf '%s\\n' "$_bin"`,
  );
  lines.push(`end`);
  lines.push(``);
  lines.push(`function __${fn}_node_compile_cache_dir`);
  lines.push(`    if set -q NODE_COMPILE_CACHE; and test -n "$NODE_COMPILE_CACHE"`);
  lines.push(`        printf '%s\\n' "$NODE_COMPILE_CACHE"`);
  lines.push(`        return 0`);
  lines.push(`    end`);
  lines.push(compileCacheDefault);
  lines.push(`end`);
  lines.push(``);
  lines.push(`function __${fn}_static_worker_path`);
  lines.push(workerPathDefault);
  lines.push(`end`);
  lines.push(``);
  lines.push(`function __${fn}_bin_sig`);
  lines.push(`    set -l _bin $argv[1]`);
  lines.push(
    `    set -l _sig (stat -L -c '%Y' "$_bin" 2>/dev/null; or stat -L -f '%m' "$_bin" 2>/dev/null)`,
  );
  lines.push(`    test -n "$_sig"; and printf '%s\\n' "$_sig"`);
  lines.push(`end`);
  lines.push(``);
  lines.push(`function __${fn}_apply_dynamic_output`);
  lines.push(`    set -l _cur $argv[1]`);
  lines.push(`    set -l _directive 0`);
  lines.push(`    set -l _emitted 0`);
  lines.push(`    set -l _exts`);
  lines.push(`    set -l _matchers`);
  lines.push(`    set -l _prev ""`);
  lines.push(`    set -l _has_prev 0`);
  lines.push(`    while read -l _l`);
  lines.push(`        if test $_has_prev -eq 1`);
  lines.push(`            if test -n "$_prev"`);
  lines.push(`                if string match -q '@ext:*' -- "$_prev"`);
  lines.push(`                    set _exts (string split , -- (string sub -s 6 -- "$_prev"))`);
  lines.push(`                else if string match -q '@matcher:*' -- "$_prev"`);
  lines.push(
    `                    set _matchers (string split , -- (string sub -s 10 -- "$_prev"))`,
  );
  lines.push(`                else`);
  lines.push(`                    printf '%s\\n' "$_prev"`);
  lines.push(`                    set _emitted 1`);
  lines.push(`                end`);
  lines.push(`            end`);
  lines.push(`        end`);
  lines.push(`        set _prev $_l`);
  lines.push(`        set _has_prev 1`);
  lines.push(`    end`);
  lines.push(`    if test $_has_prev -eq 1`);
  lines.push(`        if string match -qr '^:[0-9]+$' -- $_prev`);
  lines.push(`            set _directive (string sub -s 2 -- $_prev)`);
  lines.push(`        else if test -n "$_prev"`);
  lines.push(`            if string match -q '@ext:*' -- "$_prev"`);
  lines.push(`                set _exts (string split , -- (string sub -s 6 -- "$_prev"))`);
  lines.push(`            else if string match -q '@matcher:*' -- "$_prev"`);
  lines.push(`                set _matchers (string split , -- (string sub -s 10 -- "$_prev"))`);
  lines.push(`            else`);
  lines.push(`                printf '%s\\n' "$_prev"`);
  lines.push(`                set _emitted 1`);
  lines.push(`            end`);
  lines.push(`        end`);
  lines.push(`    end`);
  lines.push(`    if test (count $_exts) -gt 0; or test (count $_matchers) -gt 0`);
  lines.push(`        __fish_complete_directories "$_cur"`);
  lines.push(`        set -l _dir ""`);
  lines.push(`        if string match -q '*/*' "$_cur"`);
  lines.push(`            set _dir (string replace -r '[^/]*$' '' "$_cur")`);
  lines.push(`        end`);
  lines.push(`        for _ext in $_exts`);
  lines.push(`            for _f in "$_cur"*.$_ext`);
  lines.push(`                test -f "$_f"; and printf '%s\\n' "$_f"`);
  lines.push(`            end`);
  lines.push(`        end`);
  lines.push(`        for _pat in $_matchers`);
  lines.push(`            for _f in "$_dir"$_pat`);
  lines.push(
    `                test -f "$_f"; and string match -q "$_cur*" "$_f"; and printf '%s\\n' "$_f"`,
  );
  lines.push(`            end`);
  lines.push(`        end`);
  lines.push(
    `    else if test (math "bitand($_directive, ${CompletionDirective.DirectoryCompletion})") -ne 0`,
  );
  lines.push(`        __fish_complete_directories "$_cur"`);
  lines.push(
    `    else if test (math "bitand($_directive, ${CompletionDirective.FileCompletion})") -ne 0`,
  );
  lines.push(`        __fish_complete_path "$_cur"`);
  lines.push(
    `    else if test $_emitted -eq 0; and test (math "bitand($_directive, ${CompletionDirective.NoFileCompletion})") -eq 0`,
  );
  lines.push(`        __fish_complete_path "$_cur"`);
  lines.push(`    end`);
  lines.push(`end`);
  lines.push(``);
  lines.push(`function __fish_${fn}_complete`);
  lines.push(`    set -l _bin (__${fn}_resolve_bin)`);
  lines.push(`    test -n "$_bin"; or return 0`);
  lines.push(`    set -l _node_compile_cache (__${fn}_node_compile_cache_dir)`);
  lines.push(`    set -l _worker (__${fn}_static_worker_path)`);
  lines.push(`    set -l _sig (__${fn}_bin_sig "$_bin")`);
  lines.push(`    if test -n "$_worker"; and test -n "$_sig"`);
  lines.push(
    `        if not test -f "$_worker"; or not head -n 10 "$_worker" 2>/dev/null | grep -qF "# politty-bin-sig: $_sig"`,
  );
  lines.push(`            mkdir -p (dirname "$_worker") 2>/dev/null`);
  lines.push(
    `            env NODE_COMPILE_CACHE="$_node_compile_cache" ${envName}="$_bin" $_bin __refresh-completion fish "$_worker" --static --worker 2>/dev/null`,
  );
  lines.push(`        end`);
  lines.push(`        if test -f "$_worker"`);
  lines.push(`            source "$_worker" 2>/dev/null`);
  lines.push(`            if functions -q __fish_${workerFn}_complete`);
  lines.push(`                set -lx ${workerBinEnvName} "$_bin"`);
  lines.push(`                __fish_${workerFn}_complete`);
  lines.push(`                return 0`);
  lines.push(`            end`);
  lines.push(`        end`);
  lines.push(`    end`);
  lines.push(`    set -l _args (commandline -opc)`);
  lines.push(`    set -l _cur (commandline -ct)`);
  lines.push(`    if test (count $_args) -gt 0`);
  lines.push(`        set _args $_args[2..]`);
  lines.push(`    end`);
  lines.push(
    `    env NODE_COMPILE_CACHE="$_node_compile_cache" $_bin __complete --shell fish -- $_args "$_cur" 2>/dev/null | __${fn}_apply_dynamic_output "$_cur"`,
  );
  lines.push(`end`);
  lines.push(``);
  lines.push(`complete -e -c ${programName}`);
  lines.push(`complete -c ${programName} -f -a '(__fish_${fn}_complete)'`);
  lines.push(``);

  return {
    script: lines.join("\n"),
    shell: "fish",
    installInstructions: `# To enable dispatcher fish completions, run:
${programName} completion fish --install

# To generate the older static script:
${programName} completion fish --static`,
  };
}

export function generateDispatcherCompletion(
  command: AnyCommand,
  options: CompletionOptions,
): CompletionResult {
  switch (options.shell) {
    case "bash":
      return bashDispatcher(command, options);
    case "zsh":
      return zshDispatcher(command, options);
    case "fish":
      return fishDispatcher(command, options);
    default:
      throw new Error(`Unsupported shell: ${options.shell}`);
  }
}
