/**
 * Fish completion script generator (dynamic)
 */

import type { AnyCommand } from "../types.js";
import type { CompletionOptions, CompletionResult } from "./types.js";

/**
 * Generate fish completion script for a command
 *
 * Generates a minimal script that delegates all logic to the CLI's __complete command.
 * The shell script only handles:
 * - Getting current command line tokens
 * - Calling __complete with --shell fish
 * - Echoing output as completions
 * - Falling back to native file/directory completion when directed
 */
export function generateFishCompletion(
  _command: AnyCommand,
  options: CompletionOptions,
): CompletionResult {
  const programName = options.programName;

  return {
    script: `# Fish completion for ${programName}
# Generated by politty

function __fish_${programName}_complete
    set -l args (commandline -opc)
    set -e args[1]
    set -l directive 0
    set -l extensions ""

    # When cursor is after a space (new word), add empty arg
    # so __complete knows we are completing a new value, not the previous token
    if test -z (commandline -ct)
        set -a args ""
    end

    for line in (${programName} __complete --shell fish -- $args 2>/dev/null)
        if string match -q ':*' -- $line
            set directive (string sub -s 2 -- $line)
        else if string match -q '@ext:*' -- $line
            set extensions (string sub -s 6 -- $line)
        else if test -n "$line"
            echo $line
        end
    end

    # 16 = FileCompletion
    if test (math "bitand($directive, 16)") -ne 0
        __fish_complete_path
    end
    # 32 = DirectoryCompletion
    if test (math "bitand($directive, 32)") -ne 0
        __fish_complete_directories
    end

    # Extension-filtered file completion
    if test -n "$extensions"
        set -l cur (commandline -ct)
        # Ensure cur is at least an empty string (commandline may output nothing)
        test (count $cur) -eq 0; and set cur ""
        __fish_complete_directories "$cur"
        for ext in (string split "," -- $extensions)
            for f in "$cur"*.$ext
                if test -f "$f"
                    echo $f
                end
            end
        end
    end
end

# Clear existing completions
complete -e -c ${programName}

# Register completion
complete -c ${programName} -f -a '(__fish_${programName}_complete)'
`,
    shell: "fish",
    installInstructions: `# To enable completions, run one of the following:

# Option 1: Source directly
${programName} completion fish | source

# Option 2: Save to the fish completions directory
${programName} completion fish > ~/.config/fish/completions/${programName}.fish

# The completion will be available immediately in new shell sessions.
# To use in the current session, run:
source ~/.config/fish/completions/${programName}.fish`,
  };
}
