/**
 * Fish completion script generator (dynamic)
 */

import type { AnyCommand } from "../types.js";
import type { CompletionOptions, CompletionResult } from "./types.js";

/**
 * Generate fish completion script for a command
 *
 * Generates a dynamic script that calls the CLI's __complete command at runtime.
 */
export function generateFishCompletion(
  _command: AnyCommand,
  options: CompletionOptions,
): CompletionResult {
  const programName = options.programName;

  return {
    script: `# Fish completion for ${programName}
# Generated by politty
# This script calls the CLI to generate completions dynamically

function __fish_${programName}_complete
    # Get current command line arguments
    set -l args (commandline -opc)
    # Remove the program name
    set -e args[1]

    # Call the CLI to get completions
    set -l directive 0
    set -l command_completion

    for line in (${programName} __complete -- $args 2>/dev/null)
        if string match -q ':*' -- $line
            # Parse directive
            set directive (string sub -s 2 -- $line)
        else if string match -q '__command:*' -- $line
            # Parse shell command completion request
            set command_completion (string sub -s 11 -- $line)
        else if test -n "$line"
            # Parse completion: value\\tdescription
            set -l parts (string split \\t -- $line)
            if test (count $parts) -ge 2
                echo $parts[1]\\t$parts[2]
            else
                echo $parts[1]
            end
        end
    end

    # Execute shellCommand completion if requested by __complete
    if test -n "$command_completion"
        for command_candidate in (eval "$command_completion" 2>/dev/null)
            if test -n "$command_candidate"
                echo $command_candidate
            end
        end
    end

    # Handle directives by returning special values
    # The main completion function will check for these
    if test (math "$directive & 16") -ne 0
        echo "__directive:file"
    else if test (math "$directive & 32") -ne 0
        echo "__directive:directory"
    end
end

# Clear existing completions
complete -e -c ${programName}

# Main completion
complete -c ${programName} -f -a '(
    set -l completions (__fish_${programName}_complete)
    for c in $completions
        if string match -q "__directive:file" -- $c
            __fish_complete_path
        else if string match -q "__directive:directory" -- $c
            __fish_complete_directories
        else
            echo $c
        end
    end
)'
`,
    shell: "fish",
    installInstructions: `# To enable completions, run one of the following:

# Option 1: Source directly
${programName} completion fish | source

# Option 2: Save to the fish completions directory
${programName} completion fish > ~/.config/fish/completions/${programName}.fish

# The completion will be available immediately in new shell sessions.
# To use in the current session, run:
source ~/.config/fish/completions/${programName}.fish`,
  };
}
