/**
 * Static-script header utilities.
 *
 * Every completion script generated by politty starts with a small
 * machine-readable header. The rc loader and the runMain background
 * refresh path use the `# politty-bin-sig:` line to detect when the
 * cached script is stale relative to the binary on disk.
 */

import { statSync } from "node:fs";
import type { ShellType } from "./types.js";

/** Schema version of the header itself. Bump when the header layout changes. */
export const COMPLETION_VERSION = 1;

/**
 * Read the binary's mtime in whole seconds (matches POSIX `stat -c %Y` /
 * BSD `stat -f %m`). Returns `"0"` on failure so the header is always
 * well-formed.
 */
export function computeBinSig(binPath: string): string {
  try {
    return Math.floor(statSync(binPath).mtimeMs / 1000).toString();
  } catch {
    return "0";
  }
}

export interface HeaderOptions {
  programName: string;
  shell: ShellType;
  binPath?: string | undefined;
  programVersion?: string | undefined;
}

/**
 * Build the header lines (no trailing blank line). Returned without a
 * leading `#!` so each generator can prepend its own shebang/compdef
 * marker.
 */
export function buildHeaderLines(opts: HeaderOptions): string[] {
  const binPath = opts.binPath ?? process.argv[1] ?? "";
  const sig = binPath ? computeBinSig(binPath) : "0";
  const lines = [
    `# politty-completion-version: ${COMPLETION_VERSION}`,
    `# politty-bin-sig: ${sig}`,
    `# program: ${opts.programName}`,
  ];
  if (opts.programVersion) {
    lines.push(`# program-version: ${opts.programVersion}`);
  }
  lines.push(`# shell: ${opts.shell}`);
  return lines;
}
