/**
 * Static-script header utilities.
 *
 * Every completion script generated by politty starts with a small
 * machine-readable header. The rc loader and the runMain background
 * refresh path use the `# politty-bin-sig:` line to detect when the
 * cached script is stale relative to the binary on disk.
 */

import { statSync } from "node:fs";
import { join } from "node:path";
import { binEnvVarName, sanitize } from "./extractor.js";
import type { ShellType } from "./types.js";

/** Schema version of the header itself. Bump when the header layout changes. */
export const COMPLETION_VERSION = 1;

/**
 * Read the binary's mtime in whole seconds (matches POSIX `stat -c %Y` /
 * BSD `stat -f %m`). Returns `"0"` on failure so the header is always
 * well-formed.
 */
export function computeBinSig(binPath: string): string {
  try {
    return Math.floor(statSync(binPath).mtimeMs / 1000).toString();
  } catch {
    return "0";
  }
}

/**
 * Walk `$PATH` looking for an executable named `programName`. Returns
 * the first match's full path, or `null` when not found. We mirror the
 * shell's `command -v <prog>` here so the sig embedded in the header
 * (computed by Node) lines up with what the rc loader stat-checks at
 * runtime — including pnpm/npm bin shims that wrap the real entrypoint.
 * Without this alignment, shimmed installs would never match the
 * embedded sig and the cache would regenerate on every shell startup.
 */
function findOnPath(programName: string): string | null {
  // eslint-disable-next-line no-control-regex -- intentional null-byte rejection to block path injection in `programName`
  if (!programName || /[/\\\0]/.test(programName)) return null;
  const path = process.env.PATH ?? "";
  for (const dir of path.split(":")) {
    if (!dir) continue;
    const candidate = join(dir, programName);
    try {
      if (statSync(candidate).isFile()) return candidate;
    } catch {
      // skip
    }
  }
  return null;
}

/**
 * Resolve the binary path used for sig computation and stat checks.
 *
 * Order: explicit override → `$PATH` lookup of `programName` → `process.argv[1]`.
 * The `$PATH` lookup keeps Node-side and shell-side stats pointed at the
 * same shim file when the CLI is invoked through a package-manager bin shim.
 */
export function resolveBinPath(programName: string, override?: string | undefined): string {
  if (override) return override;
  const envOverride = process.env[binEnvVarName(sanitize(programName))];
  if (envOverride) return envOverride;
  return findOnPath(programName) ?? process.argv[1] ?? "";
}

export interface HeaderOptions {
  programName: string;
  shell: ShellType;
  binPath?: string | undefined;
  programVersion?: string | undefined;
}

/**
 * Build the header lines (no trailing blank line). Returned without a
 * leading `#!` so each generator can prepend its own shebang/compdef
 * marker.
 */
export function buildHeaderLines(opts: HeaderOptions): string[] {
  const sig = computeBinSig(resolveBinPath(opts.programName, opts.binPath));
  const lines = [
    `# politty-completion-version: ${COMPLETION_VERSION}`,
    `# politty-bin-sig: ${sig}`,
    `# program: ${opts.programName}`,
  ];
  if (opts.programVersion) {
    lines.push(`# program-version: ${opts.programVersion}`);
  }
  lines.push(`# shell: ${opts.shell}`);
  return lines;
}
