/**
 * Zsh completion script generator (dynamic)
 */

import type { AnyCommand } from "../types.js";
import type { CompletionOptions, CompletionResult } from "./types.js";

/**
 * Generate zsh completion script for a command
 *
 * Generates a minimal script that delegates all logic to the CLI's __complete command.
 * The shell script only handles:
 * - Getting current command line tokens
 * - Calling __complete with --shell zsh
 * - Passing output directly to _describe
 * - Falling back to native file/directory completion when directed
 */
export function generateZshCompletion(
  _command: AnyCommand,
  options: CompletionOptions,
): CompletionResult {
  const programName = options.programName;

  return {
    script: `#compdef ${programName}

# Zsh completion for ${programName}
# Generated by politty

_${programName}() {
    local -a candidates
    local line directive=0
    local -a args=("\${words[@]:1}")
    local -a output=("\${(@f)$(${programName} __complete --shell zsh -- "\${args[@]}" 2>/dev/null)}")

    local extensions=""
    for line in "\${output[@]}"; do
        if [[ "$line" == :* ]]; then
            directive="\${line:1}"
        elif [[ "$line" == @ext:* ]]; then
            extensions="\${line:5}"
        elif [[ -n "$line" ]]; then
            candidates+=("$line")
        fi
    done

    # 16 = FileCompletion: delegate entirely to native file completion
    if (( directive & 16 )); then
        _files
        return
    fi

    # Extension-filtered file completion using native _files -g
    if [[ -n "$extensions" ]]; then
        local ext_list="\${extensions//,/|}"
        if [[ "$ext_list" == *"|"* ]]; then
            _files -g "*.(\${ext_list})"
        else
            _files -g "*.$ext_list"
        fi
        return
    fi

    if (( \${#candidates[@]} > 0 )); then
        _describe 'completions' candidates
    fi

    # 32 = DirectoryCompletion: add native directory matches
    if (( directive & 32 )); then
        _files -/
    fi

    # 2 = NoFileCompletion, 32 = DirectoryCompletion:
    # prevent fallback to default completers (e.g. file completion)
    if (( directive & 2 )) || (( directive & 32 )); then
        return
    fi
}

compdef _${programName} ${programName}
`,
    shell: "zsh",
    installInstructions: `# To enable completions, add the following to your ~/.zshrc:

# Option 1: Source directly (add before compinit)
eval "$(${programName} completion zsh)"

# Option 2: Save to a file in your fpath
${programName} completion zsh > ~/.zsh/completions/_${programName}

# Make sure your fpath includes the completions directory:
# fpath=(~/.zsh/completions $fpath)
# autoload -Uz compinit && compinit

# Then reload your shell or run:
source ~/.zshrc`,
  };
}
