/**
 * Zsh completion script generator (dynamic)
 */

import type { AnyCommand } from "../types.js";
import type { CompletionOptions, CompletionResult } from "./types.js";

/**
 * Generate zsh completion script for a command
 *
 * Generates a dynamic script that calls the CLI's __complete command at runtime.
 */
export function generateZshCompletion(
  _command: AnyCommand,
  options: CompletionOptions,
): CompletionResult {
  const programName = options.programName;

  return {
    script: `#compdef ${programName}

# Zsh completion for ${programName}
# Generated by politty

_${programName}() {
    local -a candidates
    local output line directive=0
    local command_completion=""
    local file_extensions=""

    # Get the current words being completed
    local -a args
    args=("\${words[@]:1}")

    # Call the CLI to get completions
    output=("\${(@f)$(${programName} __complete -- "\${args[@]}" 2>/dev/null)}")

    # Parse output
    for line in "\${output[@]}"; do
        if [[ "$line" == :* ]]; then
            directive="\${line:1}"
        elif [[ "$line" == __command:* ]]; then
            command_completion="\${line#__command:}"
        elif [[ "$line" == __extensions:* ]]; then
            file_extensions="\${line#__extensions:}"
        elif [[ -n "$line" ]]; then
            local name="\${line%%$'\\t'*}"
            local desc="\${line#*$'\\t'}"
            if [[ "$name" == "$desc" ]]; then
                candidates+=("$name")
            else
                candidates+=("$name:$desc")
            fi
        fi
    done

    # Execute shellCommand completion if requested by __complete
    if [[ -n "$command_completion" ]]; then
        local command_candidate
        for command_candidate in "\${(@f)$(eval "$command_completion" 2>/dev/null)}"; do
            if [[ -n "$command_candidate" ]]; then
                candidates+=("$command_candidate")
            fi
        done
    fi

    # Handle directives
    # 16 = FileCompletion, 32 = DirectoryCompletion
    if (( directive & 16 )); then
        _files
    elif (( directive & 32 )); then
        _files -/
    elif (( \${#candidates[@]} > 0 )); then
        _describe 'completions' candidates
    fi
}

compdef _${programName} ${programName}
`,
    shell: "zsh",
    installInstructions: `# To enable completions, add the following to your ~/.zshrc:

# Option 1: Source directly (add before compinit)
eval "$(${programName} completion zsh)"

# Option 2: Save to a file in your fpath
${programName} completion zsh > ~/.zsh/completions/_${programName}

# Make sure your fpath includes the completions directory:
# fpath=(~/.zsh/completions $fpath)
# autoload -Uz compinit && compinit

# Then reload your shell or run:
source ~/.zshrc`,
  };
}
