/**
 * Generator for compile-cache bin shims.
 *
 * Emits the minimal entry file described in docs/recipes.md ("Faster
 * Startup"): a shim that enables the Node.js on-disk compile cache via
 * `politty/compile-cache` and then loads the real CLI with a dynamic
 * import. Meant to be wired into a `postbuild` or `prepack` script via
 * `politty generate-shim` so the shim never has to live in source.
 */

import { chmodSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

/**
 * Options for {@link generateCompileCacheShim}.
 */
export interface GenerateCompileCacheShimOptions {
  /**
   * Module specifier the shim imports to start the CLI, relative to the
   * generated shim file (e.g. `./cli.js`).
   */
  entry: string;
  /** Output path for the generated shim (e.g. `dist/bin.js`). */
  out: string;
  /**
   * Program name used to derive the cache directory. Defaults to the first
   * `bin` name in the nearest `package.json`, falling back to the package
   * name without its scope.
   */
  program?: string;
  /** Base directory for resolving paths and `package.json` (default: `process.cwd()`). */
  cwd?: string;
}

/**
 * Result of {@link generateCompileCacheShim}.
 */
export interface GenerateCompileCacheShimResult {
  /** Absolute path of the generated shim. */
  outputPath: string;
  /** Program name baked into the shim. */
  program: string;
  /** Entry specifier baked into the shim. */
  entry: string;
}

interface PackageJsonLike {
  name?: unknown;
  type?: unknown;
  bin?: unknown;
}

function readPackageJson(cwd: string): PackageJsonLike | undefined {
  try {
    return JSON.parse(readFileSync(resolve(cwd, "package.json"), "utf8")) as PackageJsonLike;
  } catch {
    return undefined;
  }
}

/**
 * Derive the default program name from a package.json: the first `bin`
 * command name when present (that is the name users type in their shell),
 * else the package name without its scope.
 */
function defaultProgramName(pkg: PackageJsonLike | undefined): string | undefined {
  if (!pkg) return undefined;
  if (typeof pkg.bin === "object" && pkg.bin !== null) {
    const [first] = Object.keys(pkg.bin);
    if (first) return first;
  }
  if (typeof pkg.name === "string" && pkg.name) {
    const name = pkg.name;
    return name.startsWith("@") ? (name.split("/")[1] ?? name) : name;
  }
  return undefined;
}

function shimContent(program: string, entry: string): string {
  return [
    "#!/usr/bin/env node",
    "",
    "// Generated by politty. Enables the Node.js on-disk compile cache (V8 code",
    "// cache) before the CLI module graph is compiled, so warm starts skip",
    "// recompilation (Node >= 22.8.0; silent no-op otherwise).",
    'import { enableCompileCache } from "politty/compile-cache";',
    "",
    `enableCompileCache(${JSON.stringify(program)});`,
    `await import(${JSON.stringify(entry)});`,
    "",
  ].join("\n");
}

/**
 * Generate an executable compile-cache bin shim.
 *
 * The generated file is ESM (it uses top-level `await import`), so `.js`
 * output requires `"type": "module"` in the package; use a `.mjs` extension
 * otherwise.
 */
export function generateCompileCacheShim(
  options: GenerateCompileCacheShimOptions,
): GenerateCompileCacheShimResult {
  const cwd = options.cwd ?? process.cwd();
  const outputPath = isAbsolute(options.out) ? options.out : resolve(cwd, options.out);
  const pkg = readPackageJson(cwd);

  const program = options.program ?? defaultProgramName(pkg);
  if (!program) {
    throw new Error(
      "Cannot derive a program name: no bin or name in package.json. Pass --program explicitly.",
    );
  }

  if (outputPath.endsWith(".cjs")) {
    throw new Error(
      'The generated shim is an ES module and cannot be written to a .cjs file. Use a .mjs (or .js in a "type": "module" package) output path.',
    );
  }
  if (outputPath.endsWith(".js") && pkg?.type !== "module") {
    throw new Error(
      'The generated shim is an ES module, but the package is not "type": "module". Write it to a .mjs file instead (e.g. --out dist/bin.mjs).',
    );
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, shimContent(program, options.entry));
  chmodSync(outputPath, 0o755);

  return { outputPath, program, entry: options.entry };
}

/**
 * Format a generated path for CLI output: relative to `cwd` when inside it.
 */
export function formatShimPath(outputPath: string, cwd: string): string {
  const rel = relative(cwd, outputPath);
  return rel && !rel.startsWith("..") ? rel : outputPath;
}
