/**
 * Generator for compile-cache bin shims.
 *
 * Emits the minimal entry file described in docs/recipes.md ("Faster
 * Startup"): a shim that enables the Node.js on-disk compile cache via
 * `politty/compile-cache` and then loads the real CLI with a dynamic
 * import. Meant to be wired into a `postbuild` or `prepack` script via
 * `politty generate-shim` so the shim never has to live in source.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";

/** Marker line identifying files this generator wrote (overwrite guard). */
const SHIM_MARKER = "Generated by politty";

/** Entry candidates tried, in order, when `entry` is omitted. */
const DEFAULT_ENTRY_CANDIDATES = ["./cli.js", "./cli.mjs", "./index.js", "./index.mjs"] as const;

/**
 * Options for {@link generateCompileCacheShim}.
 */
export interface GenerateCompileCacheShimOptions {
  /**
   * Module specifier the shim imports to start the CLI, relative to the
   * generated shim file (e.g. `./cli.js`). Defaults to the first of
   * `./cli.js`, `./cli.mjs`, `./index.js`, `./index.mjs` that exists next
   * to the shim.
   */
  entry?: string;
  /**
   * Output path for the generated shim (e.g. `dist/bin.js`). Defaults to
   * the first `bin` path in the nearest `package.json` — the place the
   * executable must live.
   */
  out?: string;
  /**
   * Program name used to derive the cache directory. Defaults to the first
   * `bin` name in the nearest `package.json`, falling back to the package
   * name without its scope.
   */
  program?: string;
  /**
   * Base directory for resolving paths and locating the nearest
   * `package.json` (default: `process.cwd()`).
   */
  cwd?: string;
}

/**
 * Result of {@link generateCompileCacheShim}.
 */
export interface GenerateCompileCacheShimResult {
  /** Absolute path of the generated shim. */
  outputPath: string;
  /** Program name baked into the shim. */
  program: string;
  /** Entry specifier baked into the shim. */
  entry: string;
}

interface PackageJsonLike {
  name?: unknown;
  type?: unknown;
  bin?: unknown;
}

interface FoundPackageJson {
  pkg: PackageJsonLike;
  /** Directory containing the package.json (base for its relative paths). */
  dir: string;
}

/**
 * Read the nearest `package.json`, walking up from `startDir` to the
 * filesystem root. A malformed file is a real error and propagates.
 */
function readNearestPackageJson(startDir: string): FoundPackageJson | undefined {
  let dir = resolve(startDir);
  for (;;) {
    const candidate = join(dir, "package.json");
    if (existsSync(candidate)) {
      return { pkg: JSON.parse(readFileSync(candidate, "utf8")) as PackageJsonLike, dir };
    }
    const parent = dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

/**
 * Derive the default program name from a package.json: the first `bin`
 * command name when present (that is the name users type in their shell),
 * else the package name without its scope.
 */
function defaultProgramName(pkg: PackageJsonLike | undefined): string | undefined {
  if (!pkg) return undefined;
  if (typeof pkg.bin === "object" && pkg.bin !== null) {
    const [first] = Object.keys(pkg.bin);
    if (first) return first;
  }
  if (typeof pkg.name === "string" && pkg.name) {
    const name = pkg.name;
    return name.startsWith("@") ? (name.split("/")[1] ?? name) : name;
  }
  return undefined;
}

/**
 * First `bin` path in a package.json: the object form's first value, or the
 * string form itself.
 */
function firstBinPath(pkg: PackageJsonLike | undefined): string | undefined {
  if (!pkg) return undefined;
  if (typeof pkg.bin === "string" && pkg.bin) return pkg.bin;
  if (typeof pkg.bin === "object" && pkg.bin !== null) {
    const [first] = Object.values(pkg.bin as Record<string, unknown>);
    if (typeof first === "string" && first) return first;
  }
  return undefined;
}

/**
 * Pick the default entry: the first {@link DEFAULT_ENTRY_CANDIDATES} that
 * exists next to the shim (never the shim itself).
 */
function defaultEntry(outputPath: string): string | undefined {
  const dir = dirname(outputPath);
  const self = basename(outputPath);
  for (const candidate of DEFAULT_ENTRY_CANDIDATES) {
    if (basename(candidate) === self) continue;
    if (existsSync(join(dir, candidate))) return candidate;
  }
  return undefined;
}

function shimContent(program: string, entry: string): string {
  return [
    "#!/usr/bin/env node",
    "",
    `// ${SHIM_MARKER}. Enables the Node.js on-disk compile cache (V8 code`,
    "// cache) before the CLI module graph is compiled, so warm starts skip",
    "// recompilation (Node >= 22.8.0; silent no-op otherwise).",
    'import { enableCompileCache } from "politty/compile-cache";',
    "",
    `enableCompileCache(${JSON.stringify(program)});`,
    `await import(${JSON.stringify(entry)});`,
    "",
  ].join("\n");
}

/**
 * Generate an executable compile-cache bin shim.
 *
 * With no explicit paths, the output defaults to the package's first `bin`
 * path and the entry to a conventional built module next to it, so a bare
 * `politty generate-shim` in a `postbuild` script is usually enough.
 *
 * The generated file is ESM (it uses top-level `await import`), so `.js`
 * output requires `"type": "module"` in the package; use a `.mjs` extension
 * otherwise. Refuses to overwrite an existing file it did not generate, so
 * a `bin` path still pointing at the real CLI entry fails loudly instead of
 * clobbering the build output.
 */
export function generateCompileCacheShim(
  options: GenerateCompileCacheShimOptions = {},
): GenerateCompileCacheShimResult {
  const cwd = options.cwd ?? process.cwd();
  const found = readNearestPackageJson(cwd);
  const pkg = found?.pkg;

  let outputPath: string;
  if (options.out !== undefined) {
    outputPath = isAbsolute(options.out) ? options.out : resolve(cwd, options.out);
  } else {
    const binPath = firstBinPath(pkg);
    if (binPath === undefined || found === undefined) {
      throw new Error(
        "Cannot derive the output path: no bin entry in package.json. Pass --out explicitly.",
      );
    }
    // bin paths are relative to the package.json that declares them.
    outputPath = resolve(found.dir, binPath);
  }

  const program = options.program ?? defaultProgramName(pkg);
  if (!program) {
    throw new Error(
      "Cannot derive a program name: no bin or name in package.json. Pass --program explicitly.",
    );
  }

  if (outputPath.endsWith(".cjs")) {
    throw new Error(
      'The generated shim is an ES module and cannot be written to a .cjs file. Use a .mjs (or .js in a "type": "module" package) output path.',
    );
  }
  if (outputPath.endsWith(".js") && pkg?.type !== "module") {
    throw new Error(
      'The generated shim is an ES module, but the package is not "type": "module". Write it to a .mjs file instead (e.g. --out dist/bin.mjs).',
    );
  }

  const entry = options.entry ?? defaultEntry(outputPath);
  if (entry === undefined) {
    throw new Error(
      `Cannot derive an entry: none of ${DEFAULT_ENTRY_CANDIDATES.join(", ")} exist next to ${outputPath}. Pass --entry explicitly.`,
    );
  }
  if (entry.startsWith(".") && resolve(dirname(outputPath), entry) === outputPath) {
    throw new Error(
      `The shim at ${outputPath} would import itself (entry ${entry}). Point bin at a separate shim path (e.g. dist/bin.js) or pass a different --entry.`,
    );
  }
  if (existsSync(outputPath) && !readFileSync(outputPath, "utf8").includes(SHIM_MARKER)) {
    throw new Error(
      `Refusing to overwrite ${outputPath}: it exists and was not generated by politty. If bin currently points at your real CLI entry, point it at a separate shim path (e.g. dist/bin.js) or pass --out explicitly.`,
    );
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, shimContent(program, entry));
  chmodSync(outputPath, 0o755);

  return { outputPath, program, entry };
}

/**
 * Format a generated path for CLI output: relative to `cwd` when inside it.
 */
export function formatShimPath(outputPath: string, cwd: string): string {
  const rel = relative(cwd, outputPath);
  return rel && !rel.startsWith("..") ? rel : outputPath;
}
