/**
 * Generator for compile-cache bin shims.
 *
 * Emits the minimal entry file described in docs/recipes.md ("Faster
 * Startup"): a shim that enables the Node.js on-disk compile cache via
 * `politty/compile-cache` and then loads the real CLI with a dynamic
 * import. Meant to be wired into a `postbuild` or `prepack` script via
 * `politty generate-shim` so the shim never has to live in source.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, isAbsolute, join, relative, resolve } from "node:path";

/**
 * Marker identifying files this generator wrote (overwrite guard). Must be
 * shim-specific: other politty artifacts (e.g. completion scripts) also say
 * "Generated by politty", and those must never be treated as overwritable.
 */
const SHIM_MARKER = "Generated by politty: compile-cache bin shim";

/** Entry candidates tried, in order, when `entry` is omitted. */
const DEFAULT_ENTRY_CANDIDATES = ["./cli.js", "./cli.mjs", "./index.js", "./index.mjs"] as const;

/**
 * Options for {@link generateCompileCacheShim}.
 */
export interface GenerateCompileCacheShimOptions {
  /**
   * Module specifier(s) the shim imports to start the CLI, relative to the
   * generated shim file (e.g. `./cli.js`). Pass one per shim; when `out` is
   * omitted the count must match the package's `bin` entries (paired in
   * order). Defaults to the first of `./cli.js`, `./cli.mjs`, `./index.js`,
   * `./index.mjs` that exists next to each shim.
   */
  entry?: string | string[];
  /**
   * Output path(s) for the generated shim(s) (e.g. `dist/bin.js`). When
   * given, the count must match `entry` (paired in order). Defaults to all
   * `bin` paths in the nearest `package.json` — the places the executables
   * must live.
   */
  out?: string | string[];
  /**
   * Program name used to derive the cache directory, applied to every
   * generated shim. Defaults per shim to the `bin` name whose path is the
   * shim's output, falling back to the first `bin` name and then the
   * package name without its scope.
   */
  program?: string;
  /**
   * Base directory for resolving paths and locating the nearest
   * `package.json` (default: `process.cwd()`).
   */
  cwd?: string;
}

/**
 * One generated shim from {@link generateCompileCacheShim}.
 */
export interface GenerateCompileCacheShimResult {
  /** Absolute path of the generated shim. */
  outputPath: string;
  /** Program name baked into the shim. */
  program: string;
  /** Entry specifier baked into the shim. */
  entry: string;
}

interface PackageJsonLike {
  name?: unknown;
  type?: unknown;
  bin?: unknown;
}

interface FoundPackageJson {
  pkg: PackageJsonLike;
  /** Directory containing the package.json (base for its relative paths). */
  dir: string;
}

/**
 * Read the nearest `package.json`, walking up from `startDir` to the
 * filesystem root. A malformed file is a real error and propagates.
 */
function readNearestPackageJson(startDir: string): FoundPackageJson | undefined {
  let dir = resolve(startDir);
  for (;;) {
    const candidate = join(dir, "package.json");
    if (existsSync(candidate)) {
      return { pkg: JSON.parse(readFileSync(candidate, "utf8")) as PackageJsonLike, dir };
    }
    const parent = dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

/**
 * `bin` entries as `[name, path]` pairs: the object form's entries in
 * declaration order, or the string form as a single pair named after the
 * package (npm's own convention for `"bin": "path"`).
 */
function binEntries(pkg: PackageJsonLike | undefined): Array<[name: string, path: string]> {
  if (!pkg) return [];
  if (typeof pkg.bin === "string" && pkg.bin) {
    const name = defaultProgramName(pkg);
    return name ? [[name, pkg.bin]] : [];
  }
  if (typeof pkg.bin === "object" && pkg.bin !== null) {
    return Object.entries(pkg.bin as Record<string, unknown>).filter(
      (pair): pair is [string, string] => typeof pair[1] === "string" && pair[1] !== "",
    );
  }
  return [];
}

/**
 * Derive the fallback program name from a package.json: the first `bin`
 * command name when present (that is the name users type in their shell),
 * else the package name without its scope.
 */
function defaultProgramName(pkg: PackageJsonLike | undefined): string | undefined {
  if (!pkg) return undefined;
  if (typeof pkg.bin === "object" && pkg.bin !== null) {
    const [first] = Object.keys(pkg.bin);
    if (first) return first;
  }
  if (typeof pkg.name === "string" && pkg.name) {
    const name = pkg.name;
    return name.startsWith("@") ? (name.split("/")[1] ?? name) : name;
  }
  return undefined;
}

/**
 * Pick the default entry: the first {@link DEFAULT_ENTRY_CANDIDATES} that
 * exists next to the shim (never the shim itself).
 */
function defaultEntry(outputPath: string): string | undefined {
  const dir = dirname(outputPath);
  const self = basename(outputPath);
  for (const candidate of DEFAULT_ENTRY_CANDIDATES) {
    if (basename(candidate) === self) continue;
    if (existsSync(join(dir, candidate))) return candidate;
  }
  return undefined;
}

function shimContent(program: string, entry: string): string {
  return [
    "#!/usr/bin/env node",
    "",
    `// ${SHIM_MARKER}.`,
    "// Enables the Node.js on-disk compile cache (V8 code cache) before the",
    "// CLI module graph is compiled, so warm starts skip recompilation",
    "// (Node >= 22.8.0; silent no-op otherwise).",
    'import { enableCompileCache } from "politty/compile-cache";',
    "",
    `enableCompileCache(${JSON.stringify(program)});`,
    `await import(${JSON.stringify(entry)});`,
    "",
  ].join("\n");
}

function toArray(value: string | string[] | undefined): string[] {
  if (value === undefined) return [];
  return Array.isArray(value) ? value : [value];
}

/**
 * Generate executable compile-cache bin shims.
 *
 * With no explicit paths, one shim is generated per `bin` entry of the
 * nearest `package.json`, each importing a conventional built module next
 * to it — so a bare `politty generate-shim` in a `postbuild` script is
 * usually enough. Explicit `entry` values are paired in order with the
 * `bin` entries (or with explicit `out` values of the same count).
 *
 * The generated files are ESM (they use top-level `await import`), so `.js`
 * output requires `"type": "module"` in the package; use a `.mjs` extension
 * otherwise. Refuses to overwrite an existing file it did not generate, so
 * a `bin` path still pointing at the real CLI entry fails loudly instead of
 * clobbering the build output.
 */
export function generateCompileCacheShim(
  options: GenerateCompileCacheShimOptions = {},
): GenerateCompileCacheShimResult[] {
  const cwd = options.cwd ?? process.cwd();
  const found = readNearestPackageJson(cwd);
  const pkg = found?.pkg;
  const entries = toArray(options.entry);
  const outs = toArray(options.out);
  const bins = binEntries(pkg);

  let outputPaths: string[];
  if (outs.length > 0) {
    if (entries.length > 0 && entries.length !== outs.length) {
      throw new Error(
        `--entry count (${entries.length}) does not match --out count (${outs.length}); pass one --out per --entry or omit --out entirely.`,
      );
    }
    outputPaths = outs.map((out) => (isAbsolute(out) ? out : resolve(cwd, out)));
  } else {
    if (bins.length === 0 || found === undefined) {
      throw new Error(
        "Cannot derive the output path: no bin entry in package.json. Pass --out explicitly.",
      );
    }
    if (entries.length > 0 && entries.length !== bins.length) {
      throw new Error(
        `--entry count (${entries.length}) does not match the package's bin entries (${bins.length}); pass one --entry per bin (in declaration order) or matching --out paths.`,
      );
    }
    // bin paths are relative to the package.json that declares them.
    outputPaths = bins.map(([, path]) => resolve(found.dir, path));
  }

  if (new Set(outputPaths).size !== outputPaths.length) {
    throw new Error(
      "Duplicate output paths; each shim needs a distinct output file. Check the --out values (or the bin paths in package.json when --out is omitted).",
    );
  }

  const binNameByPath = new Map<string, string>();
  if (found) {
    for (const [name, path] of bins) binNameByPath.set(resolve(found.dir, path), name);
  }

  // Validate every shim before writing any, so a failure cannot leave a
  // partially generated set behind.
  const plans = outputPaths.map((outputPath, index) => {
    const program = options.program ?? binNameByPath.get(outputPath) ?? defaultProgramName(pkg);
    if (!program) {
      throw new Error(
        "Cannot derive a program name: no bin or name in package.json. Pass --program explicitly.",
      );
    }

    if (outputPath.endsWith(".cjs")) {
      throw new Error(
        'The generated shim is an ES module and cannot be written to a .cjs file. Use a .mjs (or .js in a "type": "module" package) output path.',
      );
    }
    // Extensionless files only load as ESM on runtimes with module syntax
    // detection (not available on Node 20, which politty still supports) —
    // "type": "module" does not help there either (ERR_UNKNOWN_FILE_EXTENSION).
    if (extname(outputPath) === "") {
      throw new Error(
        'The generated shim is an ES module and cannot be written to an extensionless file (it would not load on every supported Node.js version). Use a .mjs (or .js in a "type": "module" package) output path.',
      );
    }
    if (outputPath.endsWith(".js") && pkg?.type !== "module") {
      throw new Error(
        pkg === undefined
          ? "The generated shim is an ES module, and no package.json was found to confirm .js files are treated as ESM. Write it to a .mjs file instead (e.g. --out dist/bin.mjs)."
          : 'The generated shim is an ES module, but the package is not "type": "module". Write it to a .mjs file instead (e.g. --out dist/bin.mjs).',
      );
    }

    const entry = entries[index] ?? defaultEntry(outputPath);
    if (entry === undefined) {
      throw new Error(
        `Cannot derive an entry: none of ${DEFAULT_ENTRY_CANDIDATES.join(", ")} exist next to ${outputPath}. Pass --entry explicitly.`,
      );
    }
    // The shim resolves the entry against its own location at runtime, and
    // absolute filesystem paths are not portable import specifiers (Windows
    // paths like C:\... are not loadable by the ESM loader at all).
    if (!entry.startsWith("./") && !entry.startsWith("../") && !entry.startsWith("file:")) {
      throw new Error(
        `Invalid entry ${entry}: pass a specifier relative to the shim file ("./..." or "../...") or a file: URL.`,
      );
    }
    if (resolve(dirname(outputPath), entry) === outputPath) {
      throw new Error(
        `The shim at ${outputPath} would import itself (entry ${entry}). Point bin at a separate shim path (e.g. dist/bin.js) or pass a different --entry.`,
      );
    }
    if (existsSync(outputPath) && !readFileSync(outputPath, "utf8").includes(SHIM_MARKER)) {
      throw new Error(
        `Refusing to overwrite ${outputPath}: it exists and was not generated by politty. If bin currently points at your real CLI entry, point it at a separate shim path (e.g. dist/bin.js) or pass --out explicitly.`,
      );
    }

    return { outputPath, program, entry };
  });

  for (const { outputPath, program, entry } of plans) {
    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, shimContent(program, entry));
    chmodSync(outputPath, 0o755);
  }

  return plans;
}

/**
 * Format a generated path for CLI output: relative to `cwd` when inside it.
 */
export function formatShimPath(outputPath: string, cwd: string): string {
  const rel = relative(cwd, outputPath);
  return rel && !rel.startsWith("..") ? rel : outputPath;
}
