name: autofix.ci

on:
  pull_request:
    branches: [main]
    paths:
      - "package.json"

concurrency:
  group: lockfile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lockfile:
    name: Update Lockfile
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        name: Install pnpm
        with:
          standalone: true
          run_install: false
      - name: Install Node.js
        run: pnpm env use --global 24
        shell: bash
      - name: Update lockfile
        run: pnpm install --no-frozen-lockfile
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
