name: autofix.ci

on:
  pull_request:
    branches: [main]
    paths:
      - "package.json"

concurrency:
  group: lockfile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lockfile:
    name: Update Lockfile
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        name: Install pnpm
        with:
          standalone: true
          run_install: false
      - name: Install Node.js
        run: pnpm env use --global 24
        shell: bash
      - name: Update lockfile
        run: pnpm install --no-frozen-lockfile
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
