name: autofix.ci

on:
  pull_request:
    branches: [main]
    paths:
      - "package.json"

concurrency:
  group: lockfile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lockfile:
    name: Update Lockfile
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        name: Install pnpm
        with:
          standalone: true
          run_install: false
      - name: Install Node.js
        run: pnpm env use --global 24
        shell: bash
      - name: Update lockfile
        run: pnpm install --no-frozen-lockfile
      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # v1.3.3
